### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by kaltu** [bkainz/fetalReconstruction#14]
I have a freshly installed ubuntu 18 and ran apt upgrade
so my boost is now version 1.65.1, and GSL 23

However, the PVR and SVR both complaining:
`SVRreconstructionGPU: error while loading shared libraries: libgsl.so.19: cannot open shared object file: No such file or directory`

if I manually sym-linked `libgsl.so.19` to `libgsl.so`, the error becomes:
`SVRreconstructionGPU: error while loading shared libraries: libboost_program_options.so.1.58.0: cannot open shared object file: No such file or directory`
and manually ln libboost not works for this time.

I have recompiled the project and the issue persist.

How do I manually set the libs to newer version?

**Comment by kaltu** [comment]
> I have a freshly installed ubuntu 18 and ran apt upgrade
> so my boost is now version 1.65.1, and GSL 23
> 
> However, the PVR and SVR both complaining:
> `SVRreconstructionGPU: error while loading shared libraries: libgsl.so.19: cannot open shared object file: No such file or directory`
> 
> if I manually sym-linked libgsl.so to libgsl.so.23, the error becomes:
> `SVRreconstructionGPU: error while loading shared libraries: libboost_program_options.so.1.58.0: cannot open shared object file: No such file or directory`
> and manually ln libboost not works for this time.
> 
> I have recompiled the project and the issue persist.
> 
> How do I manually set the libs to newer version?

**Comment by bkainz** [comment]
you likely need to install gsl via aptitude. 
naturally, such problems become more frequent now that the repo gets older and I don't have the ressources to maintain this properly. Currently I plan to produce an AppImage for it as soon as there's less teaching in summer term, so please stay tuned.

**Comment by kaltu** [comment]
I do install all the dependencies through `apt install`

Actually, I kept a little snippet in my note for freshly installed Ubuntu to fully support this project.
Its
```
sudo ubuntu-drivers autoinstall

sudo apt install build-essential g++ python-dev autotools-dev libicu-dev libbz2-dev cmake libgsl-dev libpng-dev libboost-all-dev libtbb-dev nvidia-cuda-toolkit g++6 gcc-6 -y

sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 10
```
a bit more than your note of dependencies note to make it work.

Any way, I resolved this issue.
Simpy format the disk and reinstall Ubuntu 16.04.5 instead of Ubuntu18.
It looks like this project do not behave well in newer distro.

Maybe consider add this info to the front page?

**Comment by bkainz** [comment]
excellent. thanks for the update! I have currently an AppImage on the TODO list for this. Will post it as soon as it is ready.

**Comment by bkainz** [comment]
initial try to generate an AppImage from one of my running binaries here: https://github.com/bkainz/fetalReconstruction/releases
